### ISSUE TITLE
What did you think about the process of writing a command?

### ISSUE THREAD

**Issue by danielbachhuber** [mikedance/wp-cli-favorite-plugins#2]
What went well, and what could be improved? Any documentation changes you'd suggest?

**Comment by mikedance** [comment]
Pretty smooth overall, thanks. Documentation was good. I'd suggest mentioning wp-cli/scaffold-package-command higher in the overview of the Commands Cookbook - I didn't even notice it until after I'd finished the bulk of my command.

**Comment by danielbachhuber** [comment]
> Pretty smooth overall, thanks. Documentation was good.

Glad to hear :)

> I'd suggest mentioning wp-cli/scaffold-package-command higher in the overview of the Commands Cookbook - I didn't even notice it until after I'd finished the bulk of my command.

Good suggestion! I've updated https://github.com/wp-cli/wp-cli.github.com/commit/d20b26bfe06c53b644644bb60a5c1ed945901b51
